name: curo

version: 3.0.2

description: Powerful, modern Dart library for precise instalment credit calculations - from simple loans to advanced amortisation schedules.

homepage: https://github.com/andrewmurphy353/curo

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  intl: ^0.20.2
  meta: ^1.17.0

dev_dependencies:
  coverage: ^1.15.0
  lints: ^6.0.0
  test: ^1.29.0
