name: curo

version: 3.0.0

description: A feature-rich library for performing simple to advanced instalment credit financial calculations.

homepage: https://github.com/andrewmurphy353/curo

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  intl: ^0.20.2
  meta: ^1.18.0

dev_dependencies:
  coverage: ^1.15.0
  lints: ^6.0.0
  test: ^1.29.0
